### ISSUE TITLE
Error in Yara File.

### ISSUE THREAD

**Issue by kenetik** [Neo23x0/yarAnalyzer#2]
I added a .yar to the signatures directory and performed a scan on a directory with confirmed/known matches. After execution I received the following:

    [root@secured yarAnalyzer]# ./yarAnalyzer.py -p /home/secured/downloads/confirmedfiles/
    [ERROR]: Error in Yara file: AllMWLocker.yar
    [INFO]: Scanning /home/secured/downloads/confirmedfiles/ ...  

I also performed the same scan with the --debug flag, however no other information was given as to what the issue/error with the yara file was. Verbose output as to the error would be great.

**Comment by Neo23x0** [comment]
yarAnalyzer is no debugger for Yara rules. 
Use yara to debug the rules and then place the corrected rules in the signatures folder.
