### ISSUE TITLE
release tags

### ISSUE THREAD

**Issue by shibumi** [Neo23x0/yarAnalyzer#3]
Hello could you please use release tags? I want to package your software for the Archlinux user repository: http://aur.archlinux.org

cheers

Chris

**Comment by Neo23x0** [comment]
Have you seen my other projects?
LOKI
yarGen 

Those are far better maintained - although none has release tags.

**Comment by shibumi** [comment]
LOKI seems windows only
I will think about yarGen.

**Comment by Neo23x0** [comment]
Done. 

yarGen is big (in size). 
LOKI runs on Windows, Linux, OS X. 
The repo contains a compiled windows binary for convenience.
