### ISSUE TITLE
help.... rule iterable problem

### ISSUE THREAD

**Issue by ayebachchu** [Neo23x0/yarAnalyzer#5]
![default](https://cloud.githubusercontent.com/assets/15387307/10832848/3347957c-7ed1-11e5-9597-9179754b04a6.PNG)
please help.
I can't know what the problem is.

**Comment by Neo23x0** [comment]
Outdated yara python module version.
Download the latest yara module Windows binary package from here:
https://github.com/plusvic/yara/releases/latest

Follow "Windows binaries can be found here."
Than select the appropriate version, e.g. yara-python-3.4.0.win32-py2.7.exe

Don't use the outdated versions provided via pip or easy_install.

**Comment by ayebachchu** [comment]
thank you. I like your programs ^^
